apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-16T16:46:37Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "7048"
  uid: fb50cf12-4f7a-444c-8770-70f1dca184bf
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.111.59.146
  clusterIPs:
  - 10.111.59.146
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30440
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
